// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza_Shop.Server.Data;

namespace Pizza_Shop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220221091511_MorePizzaAdded")]
    partial class MorePizzaAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pizza_Shop.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "American",
                            Url = "america"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Italian",
                            Url = "italia"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Ekzotik",
                            Url = "ekzo"
                        });
                });

            modelBuilder.Entity("Pizza_Shop.Shared.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Neopolitano pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 9.99m,
                            Title = "Neopolitano"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "4Cheese pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 8.99m,
                            Title = "4Cheese"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Chicago Pizza pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 7.99m,
                            Title = "Chicago Pizza"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Sicilia pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 9.99m,
                            Title = "Sicilia"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Paperoni pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 8.99m,
                            Title = "Paperoni"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Поживна, з насиченим м’ясним смаком, Баварська піца стане гарною закускою до міцного німецького пива. У складі — смачнючі баварські ковбаски, вкриті скориночкою з пармезана та моцарелли. Смакота!",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 7.99m,
                            Title = "Bavarian"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Mexicano pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 9.99m,
                            Title = "Mexicano"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Mashrooms Pizza pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 11.99m,
                            Title = "Mashrooms Pizza"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Hawaiian pizza pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 7.99m,
                            Title = "Hawaiian pizza"
                        });
                });

            modelBuilder.Entity("Pizza_Shop.Shared.Pizza", b =>
                {
                    b.HasOne("Pizza_Shop.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
