// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza_Shop.Server.Data;

namespace Pizza_Shop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220218135600_PizzaSeeding")]
    partial class PizzaSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pizza_Shop.Shared.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neopolitano pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 9.99m,
                            Title = "Neopolitano"
                        },
                        new
                        {
                            Id = 2,
                            Description = "4Cheese pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 8.99m,
                            Title = "4Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chicago Pizza pizza description",
                            ImageUrl = "http://4.bp.blogspot.com/-cXJNdO0Fris/UvldtuI4nJI/AAAAAAAABQg/29wVM7OhR6U/s1600/03-Margherita-Pizza-Totale-Pizza-Napoletana.jpg",
                            Price = 7.99m,
                            Title = "Chicago Pizza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
